comment cd github actions and prometheus and grafana

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,35 +1,35 @@
-name: CD
+# name: CD
 
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+# on:
+#   push:
+#     branches: [ main ]
+#   pull_request:
+#     branches: [ main ]
 
-jobs:
-  cd:
-    runs-on: self-hosted  # ← Ваш локальный runner
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          path: my-python-app  # Checkout в поддиректорию
+# jobs:
+#   cd:
+#     runs-on: self-hosted  # ← Ваш локальный runner
+#     steps:
+#       - uses: actions/checkout@v4
+#         with:
+#           path: my-python-app  # Checkout в поддиректорию
 
-      - name: 🚀 Local Deploy
-        run: |
-          echo "🚀 Self-hosted deploy на localhost!"
+#       - name: 🚀 Local Deploy
+#         run: |
+#           echo "🚀 Self-hosted deploy на localhost!"
           
-          cd /home/ilyatychinin/devops_train_projects/my-python-app || exit 1
+#           cd /home/ilyatychinin/devops_train_projects/my-python-app || exit 1
           
-          git pull origin main
+#           git pull origin main
           
-          docker compose down
+#           docker compose down
           
-          docker compose up -d
+#           docker compose up -d
           
-          sleep 10
+#           sleep 10
           
-          curl -f http://localhost:8080/health || echo "Health check failed"
+#           curl -f http://localhost:8080/health || echo "Health check failed"
           
-          docker compose ps
+#           docker compose ps
           
-          echo "✅ Deploy complete!"
+#           echo "✅ Deploy complete!"
